package Visual;

import Modelo.DAOEstoque;
import Modelo.Estoque;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Josi
 */
public class FormEstoque extends javax.swing.JDialog {

    DAOEstoque daoEstoque = new DAOEstoque();
    
    /**
     * Creates new form FormEstoque
     */
    public FormEstoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizaTabela();
        trataEdicao(false);
    }

    public boolean validaCampos() {
        if (!(txtNomeEstoque.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe o nome da peça");
            txtNomeEstoque.requestFocus();
            return false;
        }
        if (!(txtValorEstoque.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe o valor da peça");
            txtValorEstoque.requestFocus();
            return false;
        }
        if (!(txtQuantidadeEstoque.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade da peça");
            txtQuantidadeEstoque.requestFocus();
            return false;
        }
        return true;
    }
    
    private void trataEdicao(boolean editando) {
        btnCancelarEstoque.setEnabled(editando);
        btnSalvarEstoque.setEnabled(editando);
        btnEditarEstoque.setEnabled(!editando);
        int linha = listaEstoque.size() - 1;
        if (linha < 0) {
            btnExcluirEstoque.setEnabled(false);
            txtCodigoEstoque.setText("");
            txtNomeEstoque.setText("");
            txtValorEstoque.setText("");
            txtQuantidadeEstoque.setText("");
        } else {
            btnExcluirEstoque.setEnabled(!editando);
        }
        btnExcluirEstoque.setEnabled(!editando);
        btnNovoEstoque.setEnabled(!editando);
        btnFecharEstoque.setEnabled(!editando);
        btnPrimeiroEstoque.setEnabled(!editando);
        btnProximoEstoque.setEnabled(!editando);
        btnAnteriorEstoque.setEnabled(!editando);
        btnUltimoEstoque.setEnabled(!editando);
        txtNomeEstoque.setEnabled(editando);
        txtValorEstoque.setEnabled(editando);
        txtQuantidadeEstoque.setEnabled(editando);
        tblEstoque.setEnabled(editando);
    }
    
    public void atualizaTabela() {
        listaEstoque.clear();
        listaEstoque.addAll(daoEstoque.getLista());
        int linha = listaEstoque.size() - 1;
        if (linha >= 0) {
            tblEstoque.setRowSelectionInterval(linha, linha);
            tblEstoque.scrollRectToVisible(tblEstoque.getCellRect(linha, linha, true));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaEstoque = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList <Estoque> ( ) ) ;
        painelNavegacaoEstoque = new javax.swing.JPanel();
        btnPrimeiroEstoque = new javax.swing.JButton();
        btnAnteriorEstoque = new javax.swing.JButton();
        btnProximoEstoque = new javax.swing.JButton();
        btnUltimoEstoque = new javax.swing.JButton();
        btnFecharEstoque = new javax.swing.JButton();
        abasEstoque = new javax.swing.JTabbedPane();
        abaListagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstoque = new javax.swing.JTable();
        abaDados = new javax.swing.JPanel();
        painelAcoes = new javax.swing.JPanel();
        btnNovoEstoque = new javax.swing.JButton();
        btnEditarEstoque = new javax.swing.JButton();
        btnCancelarEstoque = new javax.swing.JButton();
        btnSalvarEstoque = new javax.swing.JButton();
        btnExcluirEstoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoEstoque = new javax.swing.JTextField();
        txtQuantidadeEstoque = new javax.swing.JTextField();
        txtValorEstoque = new javax.swing.JTextField();
        txtNomeEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Estoque");

        painelNavegacaoEstoque.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegação"));
        painelNavegacaoEstoque.setLayout(new java.awt.GridLayout(1, 0));

        btnPrimeiroEstoque.setText("Primeiro");
        btnPrimeiroEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroEstoqueActionPerformed(evt);
            }
        });
        painelNavegacaoEstoque.add(btnPrimeiroEstoque);

        btnAnteriorEstoque.setText("Anterior");
        btnAnteriorEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorEstoqueActionPerformed(evt);
            }
        });
        painelNavegacaoEstoque.add(btnAnteriorEstoque);

        btnProximoEstoque.setText("Próximo");
        btnProximoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoEstoqueActionPerformed(evt);
            }
        });
        painelNavegacaoEstoque.add(btnProximoEstoque);

        btnUltimoEstoque.setText("Último");
        btnUltimoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoEstoqueActionPerformed(evt);
            }
        });
        painelNavegacaoEstoque.add(btnUltimoEstoque);

        btnFecharEstoque.setText("Fechar");
        btnFecharEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharEstoqueActionPerformed(evt);
            }
        });
        painelNavegacaoEstoque.add(btnFecharEstoque);

        abaListagem.setLayout(new java.awt.BorderLayout());

        tblEstoque.setBackground(new java.awt.Color(240, 240, 240));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaEstoque, tblEstoque);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idEstoque}"));
        columnBinding.setColumnName("Id Estoque");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomePeca}"));
        columnBinding.setColumnName("Nome Peça");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidadePeca}"));
        columnBinding.setColumnName("Quantidade Peça");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorPeca}"));
        columnBinding.setColumnName("Valor Peça");
        columnBinding.setColumnClass(Double.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblEstoque);

        abaListagem.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        abasEstoque.addTab("Listagem", abaListagem);

        painelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        painelAcoes.setLayout(new java.awt.GridLayout(1, 0));

        btnNovoEstoque.setText("Novo");
        btnNovoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoEstoqueActionPerformed(evt);
            }
        });
        painelAcoes.add(btnNovoEstoque);

        btnEditarEstoque.setText("Editar");
        btnEditarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEstoqueActionPerformed(evt);
            }
        });
        painelAcoes.add(btnEditarEstoque);

        btnCancelarEstoque.setText("Cancelar");
        btnCancelarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEstoqueActionPerformed(evt);
            }
        });
        painelAcoes.add(btnCancelarEstoque);

        btnSalvarEstoque.setText("Salvar");
        btnSalvarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEstoqueActionPerformed(evt);
            }
        });
        painelAcoes.add(btnSalvarEstoque);

        btnExcluirEstoque.setText("Excluir");
        btnExcluirEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEstoqueActionPerformed(evt);
            }
        });
        painelAcoes.add(btnExcluirEstoque);

        jLabel1.setText("Código:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Nome:");

        txtCodigoEstoque.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblEstoque, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idEstoque}"), txtCodigoEstoque, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblEstoque, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.quantidadePeca}"), txtQuantidadeEstoque, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblEstoque, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.valorPeca}"), txtValorEstoque, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblEstoque, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomePeca}"), txtNomeEstoque, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout abaDadosLayout = new javax.swing.GroupLayout(abaDados);
        abaDados.setLayout(abaDadosLayout);
        abaDadosLayout.setHorizontalGroup(
            abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDadosLayout.createSequentialGroup()
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                    .addGroup(abaDadosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(abaDadosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaDadosLayout.createSequentialGroup()
                                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuantidadeEstoque)
                                    .addComponent(txtCodigoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        abaDadosLayout.setVerticalGroup(
            abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtValorEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        abasEstoque.addTab("Dados", abaDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelNavegacaoEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abasEstoque)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelNavegacaoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abasEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharEstoqueActionPerformed
        // TODO add your handling code here:
        dispose(); // fechar janela
    }//GEN-LAST:event_btnFecharEstoqueActionPerformed

    private void btnNovoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoEstoqueActionPerformed
        // TODO add your handling code here:
        listaEstoque.add((Estoque) new Estoque());
        int linha = listaEstoque.size() -1;
        tblEstoque.setRowSelectionInterval(linha, linha);
        txtNomeEstoque.requestFocus();
        trataEdicao(true);
    }//GEN-LAST:event_btnNovoEstoqueActionPerformed

    private void btnSalvarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEstoqueActionPerformed
        // TODO add your handling code here:
        if(validaCampos()){
            int linhaSelecionada = tblEstoque.getSelectedRow(); 
            Estoque obj = listaEstoque.get(linhaSelecionada);
            daoEstoque.salvar(obj); 
            atualizaTabela();
            trataEdicao(false);
        }
    }//GEN-LAST:event_btnSalvarEstoqueActionPerformed

    private void btnEditarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstoqueActionPerformed
        // TODO add your handling code here:
         trataEdicao(true);  
         txtNomeEstoque.requestFocus();
    }//GEN-LAST:event_btnEditarEstoqueActionPerformed

    private void btnCancelarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEstoqueActionPerformed
        // TODO add your handling code here:
         trataEdicao(false);        
         atualizaTabela();
    }//GEN-LAST:event_btnCancelarEstoqueActionPerformed

    private void btnExcluirEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEstoqueActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showOptionDialog(null, "Confirma a exclusão?", 
                 "Pergunta",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
                 null, new String [] {"Sim","Não"},"Sim");     
         if(opcao==0){    
             int linhaSelecionada = tblEstoque.getSelectedRow();         
             Estoque obj = listaEstoque.get(linhaSelecionada);        
             daoEstoque.remover(obj);        
             atualizaTabela();   
             trataEdicao(false);      
         } 
    }//GEN-LAST:event_btnExcluirEstoqueActionPerformed

    private void btnPrimeiroEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroEstoqueActionPerformed
        // TODO add your handling code here:
        tblEstoque.setRowSelectionInterval(0, 0);
        tblEstoque.scrollRectToVisible(tblEstoque.getCellRect(0, 0, true));
    }//GEN-LAST:event_btnPrimeiroEstoqueActionPerformed

    private void btnAnteriorEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorEstoqueActionPerformed
        // TODO add your handling code here:
        int linha = tblEstoque.getSelectedRow();
        if ((linha - 1) >= 0) {
            linha--;
        }
        tblEstoque.setRowSelectionInterval(linha, linha);
        tblEstoque.scrollRectToVisible(tblEstoque.getCellRect(linha, 0, true));                                                   
    }//GEN-LAST:event_btnAnteriorEstoqueActionPerformed

    private void btnProximoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoEstoqueActionPerformed
        // TODO add your handling code here:
        int linha = tblEstoque.getSelectedRow();
        if ((linha + 1) <= tblEstoque.getRowCount() - 1) {
            linha++;
        }
        tblEstoque.setRowSelectionInterval(linha, linha);
        tblEstoque.scrollRectToVisible(tblEstoque.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnProximoEstoqueActionPerformed

    private void btnUltimoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoEstoqueActionPerformed
        // TODO add your handling code here:
        int linha = tblEstoque.getSelectedRow();
        if ((linha + 1) <= tblEstoque.getRowCount() - 1) {
            linha++;
        }
        tblEstoque.setRowSelectionInterval(linha, linha);
        tblEstoque.scrollRectToVisible(tblEstoque.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnUltimoEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormEstoque dialog = new FormEstoque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaDados;
    private javax.swing.JPanel abaListagem;
    private javax.swing.JTabbedPane abasEstoque;
    private javax.swing.JButton btnAnteriorEstoque;
    private javax.swing.JButton btnCancelarEstoque;
    private javax.swing.JButton btnEditarEstoque;
    private javax.swing.JButton btnExcluirEstoque;
    private javax.swing.JButton btnFecharEstoque;
    private javax.swing.JButton btnNovoEstoque;
    private javax.swing.JButton btnPrimeiroEstoque;
    private javax.swing.JButton btnProximoEstoque;
    private javax.swing.JButton btnSalvarEstoque;
    private javax.swing.JButton btnUltimoEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<Estoque> listaEstoque;
    private javax.swing.JPanel painelAcoes;
    private javax.swing.JPanel painelNavegacaoEstoque;
    private javax.swing.JTable tblEstoque;
    private javax.swing.JTextField txtCodigoEstoque;
    private javax.swing.JTextField txtNomeEstoque;
    private javax.swing.JTextField txtQuantidadeEstoque;
    private javax.swing.JTextField txtValorEstoque;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
