/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Modelo.Aparelho;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Modelo.DAOAparelho;
import Modelo.Cliente;
import Modelo.DAOCliente;

/**
 *
 * @author pedri
 */
public class FormAparelho extends javax.swing.JDialog {

    DAOAparelho daoAparelho = new DAOAparelho();
    DAOCliente daoCliente = new DAOCliente();
    /**
     * Creates new form FormAparelho
     */
    public FormAparelho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizaTabela();
        trataEdicao(false);
        listCliente.clear();
        listCliente.addAll(daoCliente.getLista());
    }

    public boolean validaCampos() {
        if (!(txtNomeAparelho.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe o nome do aparelho");
            txtNomeAparelho.requestFocus();
            return false;
        }
        
        if (!(txtMarcaAparelho.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a marca do aparelho");
            txtMarcaAparelho.requestFocus();
            return false;
        }

        if (!(txtDataRecebimento.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a data de recebimento do aparelho");
            txtDataRecebimento.requestFocus();
            return false;
        }
        
        if (!(txtDataGarantia.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a data de garantia do aparelho");
            txtDataGarantia.requestFocus();
            return false;
        }
        
        if (!(cbxCliente.getSelectedIndex() >= 0)) {
            JOptionPane.showMessageDialog(null, "Informe o dono do aparelho");
            cbxCliente.requestFocus();
            return false;
        }
        return true;
    }
    
    private void trataEdicao(boolean editando) {
        btnCancelarAparelho.setEnabled(editando);
        btnSalvarAparelho.setEnabled(editando);
        btnEditarAparelho.setEnabled(!editando);
        int linha = listAparelhos.size() - 1;
        if (linha < 0) {
            btnExcluirAparelho.setEnabled(false);
            txtCodigoAparelhos.setText("");
            txtNomeAparelhos.setText("");
            txtMarcaAparelhos.setText("");
            txtDataRecebimento.setText("");
            txtDataGarantia.setText("");
        } else {
            btnExcluirAparelho.setEnabled(!editando);
        }
        btnExcluirAparelho.setEnabled(!editando);
        btnNovoAparelho.setEnabled(!editando);
        btnFecharAparelho.setEnabled(!editando);
        btnPrimeiroAparelho.setEnabled(!editando);
        btnProximoAparelho.setEnabled(!editando);
        btnAnteriorAparelho.setEnabled(!editando);
        btnUltimoAparelho.setEnabled(!editando);
        txtNomeAparelhos.setEnabled(editando);
        txtMarcaAparelhos.setEnabled(editando);
        txtDataRecebimento.setEditable(editando);
        txtDataGarantia.setEditable(editando);
        cbxCliente.setEnabled(editando);
        tblAparelho.setEnabled(editando);
    }
    
    public void atualizaTabela() {
        listAparelhos.clear();
        listAparelhos.addAll(daoAparelho.getLista());
        int linha = listAparelhos.size() - 1;
        if (linha >= 0) {
            tblAparelho.setRowSelectionInterval(linha, linha);
            tblAparelho.scrollRectToVisible(tblAparelho.getCellRect(linha, linha, true));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listAparelhos = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Aparelho>());
        listCliente = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Cliente>());
        converteData1 = new Modelo.ConverteData();
        painelNavegacao = new javax.swing.JPanel();
        btnPrimeiroAparelho = new javax.swing.JButton();
        btnAnteriorAparelho = new javax.swing.JButton();
        btnProximoAparelho = new javax.swing.JButton();
        btnUltimoAparelho = new javax.swing.JButton();
        btnFecharAparelho = new javax.swing.JButton();
        abaDados = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAparelho = new javax.swing.JTable();
        painelDadosAparelho = new javax.swing.JPanel();
        painelAcaoAparelho = new javax.swing.JPanel();
        btnNovoAparelho = new javax.swing.JButton();
        btnEditarAparelho = new javax.swing.JButton();
        btnCancelarAparelho = new javax.swing.JButton();
        btnSalvarAparelho = new javax.swing.JButton();
        btnExcluirAparelho = new javax.swing.JButton();
        txtNomeAparelhos = new javax.swing.JLabel();
        txtCodigoAparelhos = new javax.swing.JLabel();
        txtMarcaAparelhos = new javax.swing.JLabel();
        txtCodigoAparelho = new javax.swing.JTextField();
        txtNomeAparelho = new javax.swing.JTextField();
        txtMarcaAparelho = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskData = null;

        try{
            maskData = new javax.swing.text.MaskFormatter("##/##/####");
            maskData.setPlaceholderCharacter('_');
        }catch(Exception e){

        }
        txtDataRecebimento = new javax.swing.JFormattedTextField(maskData);
        javax.swing.text.MaskFormatter maskaData = null;

        try{
            maskaData = new javax.swing.text.MaskFormatter("##/##/####");
            maskaData.setPlaceholderCharacter('_');
        }catch(Exception e){

        }
        txtDataGarantia = new javax.swing.JFormattedTextField(maskaData);
        jLabel3 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Aparelhos");

        painelNavegacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegação"));
        painelNavegacao.setLayout(new java.awt.GridLayout(1, 0));

        btnPrimeiroAparelho.setText("Primeiro");
        btnPrimeiroAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroAparelhoActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnPrimeiroAparelho);

        btnAnteriorAparelho.setText("Anterior");
        btnAnteriorAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorAparelhoActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnAnteriorAparelho);

        btnProximoAparelho.setText("Próximo");
        btnProximoAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoAparelhoActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnProximoAparelho);

        btnUltimoAparelho.setText("Último");
        btnUltimoAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoAparelhoActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnUltimoAparelho);

        btnFecharAparelho.setText("Fechar");
        btnFecharAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharAparelhoActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnFecharAparelho);

        jPanel1.setLayout(new java.awt.BorderLayout());

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listAparelhos, tblAparelho);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idAparelho}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeAparelho}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marcaAparelho}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataRecebimentoFormatado}"));
        columnBinding.setColumnName("Data Recebimento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataGarantiaFormatado}"));
        columnBinding.setColumnName("Data Garantia");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idCliente}"));
        columnBinding.setColumnName("Cliente");
        columnBinding.setColumnClass(Modelo.Cliente.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblAparelho);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.PAGE_START);

        abaDados.addTab("Listagem", jPanel1);

        painelAcaoAparelho.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        painelAcaoAparelho.setLayout(new java.awt.GridLayout(1, 0));

        btnNovoAparelho.setText("Novo");
        btnNovoAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAparelhoActionPerformed(evt);
            }
        });
        painelAcaoAparelho.add(btnNovoAparelho);

        btnEditarAparelho.setText("Editar");
        btnEditarAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAparelhoActionPerformed(evt);
            }
        });
        painelAcaoAparelho.add(btnEditarAparelho);

        btnCancelarAparelho.setText("Cancelar");
        btnCancelarAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAparelhoActionPerformed(evt);
            }
        });
        painelAcaoAparelho.add(btnCancelarAparelho);

        btnSalvarAparelho.setText("Salvar");
        btnSalvarAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAparelhoActionPerformed(evt);
            }
        });
        painelAcaoAparelho.add(btnSalvarAparelho);

        btnExcluirAparelho.setText("Excluir");
        btnExcluirAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAparelhoActionPerformed(evt);
            }
        });
        painelAcaoAparelho.add(btnExcluirAparelho);

        txtNomeAparelhos.setText("Aparelho:");

        txtCodigoAparelhos.setLabelFor(abaDados);
        txtCodigoAparelhos.setText("Código:");

        txtMarcaAparelhos.setText("Marca:");

        txtCodigoAparelho.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblAparelho, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idAparelho}"), txtCodigoAparelho, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblAparelho, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomeAparelho}"), txtNomeAparelho, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblAparelho, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.marcaAparelho}"), txtMarcaAparelho, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel1.setText("Data de Garantia:");

        jLabel2.setText("Data de Recebimento:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblAparelho, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataRecebimentoAparelho}"), txtDataRecebimento, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setConverter(converteData1);
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblAparelho, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataGarantia}"), txtDataGarantia, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setConverter(converteData1);
        bindingGroup.addBinding(binding);

        jLabel3.setText("Cliente:");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listCliente, cbxCliente);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblAparelho, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idCliente}"), cbxCliente, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout painelDadosAparelhoLayout = new javax.swing.GroupLayout(painelDadosAparelho);
        painelDadosAparelho.setLayout(painelDadosAparelhoLayout);
        painelDadosAparelhoLayout.setHorizontalGroup(
            painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelAcaoAparelho, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                            .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDataRecebimento, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txtDataGarantia)
                                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtMarcaAparelhos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMarcaAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosAparelhoLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(txtCodigoAparelhos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodigoAparelho))
                                .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                                    .addComponent(txtNomeAparelhos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNomeAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        painelDadosAparelhoLayout.setVerticalGroup(
            painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                .addComponent(painelAcaoAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoAparelhos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosAparelhoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNomeAparelhos))
                    .addComponent(txtNomeAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarcaAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcaAparelhos))
                .addGap(26, 26, 26)
                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(painelDadosAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        abaDados.addTab("Dados", painelDadosAparelho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaDados, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abaDados, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharAparelhoActionPerformed
        // TODO add your handling code here:
        dispose(); //fechar janela
    }//GEN-LAST:event_btnFecharAparelhoActionPerformed

    private void btnNovoAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAparelhoActionPerformed
        // TODO add your handling code here:
        listAparelhos.add((Aparelho) new Aparelho());
        int linha = listAparelhos.size() -1;
        tblAparelho.setRowSelectionInterval(linha, linha);
        txtNomeAparelhos.requestFocus();
        trataEdicao(true);
    }//GEN-LAST:event_btnNovoAparelhoActionPerformed

    private void btnSalvarAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAparelhoActionPerformed
        // TODO add your handling code here:
        if(validaCampos()){
            int linhaSelecionada = tblAparelho.getSelectedRow(); 
            Aparelho obj = listAparelhos.get(linhaSelecionada);
            daoAparelho.salvar(obj); 
            atualizaTabela();
            trataEdicao(false);
        }     
    }//GEN-LAST:event_btnSalvarAparelhoActionPerformed

    private void btnEditarAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAparelhoActionPerformed
        // TODO add your handling code here:
        trataEdicao(true);
        txtNomeAparelhos.requestFocus();
    }//GEN-LAST:event_btnEditarAparelhoActionPerformed

    private void btnCancelarAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAparelhoActionPerformed
        // TODO add your handling code here:
        trataEdicao(false);
        atualizaTabela();
    }//GEN-LAST:event_btnCancelarAparelhoActionPerformed

    private void btnExcluirAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAparelhoActionPerformed
        // TODO add your handling code here:
         int opcao = JOptionPane.showOptionDialog(null, "Confirma a exclusão?", 
                 "Pergunta",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
                 null, new String [] {"Sim","Não"},"Sim");     
         if(opcao==0){    
             int linhaSelecionada = tblAparelho.getSelectedRow();         
             Aparelho obj = listAparelhos.get(linhaSelecionada);        
             daoAparelho.remover(obj);        
             atualizaTabela();   
             trataEdicao(false);      
         }     
    }//GEN-LAST:event_btnExcluirAparelhoActionPerformed

    private void btnPrimeiroAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroAparelhoActionPerformed
        // TODO add your handling code here:
        tblAparelho.setRowSelectionInterval(0, 0);
        tblAparelho.scrollRectToVisible(tblAparelho.getCellRect(0, 0, true));
    }//GEN-LAST:event_btnPrimeiroAparelhoActionPerformed

    private void btnAnteriorAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorAparelhoActionPerformed
        // TODO add your handling code here:
        int linha = tblAparelho.getSelectedRow();
        if ((linha - 1) >= 0) {
            linha--;
        }
        tblAparelho.setRowSelectionInterval(linha, linha);
        tblAparelho.scrollRectToVisible(tblAparelho.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnAnteriorAparelhoActionPerformed

    private void btnProximoAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoAparelhoActionPerformed
        // TODO add your handling code here:
        int linha = tblAparelho.getSelectedRow();
        if ((linha + 1) <= tblAparelho.getRowCount() - 1) {
            linha++;
        }
        tblAparelho.setRowSelectionInterval(linha, linha);
        tblAparelho.scrollRectToVisible(tblAparelho.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnProximoAparelhoActionPerformed

    private void btnUltimoAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoAparelhoActionPerformed
        // TODO add your handling code here:
        int linha = tblAparelho.getSelectedRow();
        if ((linha + 1) <= tblAparelho.getRowCount() - 1) {
            linha++;
        }
        tblAparelho.setRowSelectionInterval(linha, linha);
        tblAparelho.scrollRectToVisible(tblAparelho.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnUltimoAparelhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAparelho dialog = new FormAparelho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaDados;
    private javax.swing.JButton btnAnteriorAparelho;
    private javax.swing.JButton btnCancelarAparelho;
    private javax.swing.JButton btnEditarAparelho;
    private javax.swing.JButton btnExcluirAparelho;
    private javax.swing.JButton btnFecharAparelho;
    private javax.swing.JButton btnNovoAparelho;
    private javax.swing.JButton btnPrimeiroAparelho;
    private javax.swing.JButton btnProximoAparelho;
    private javax.swing.JButton btnSalvarAparelho;
    private javax.swing.JButton btnUltimoAparelho;
    private javax.swing.JComboBox<String> cbxCliente;
    private Modelo.ConverteData converteData1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.util.List<Aparelho> listAparelhos;
    private java.util.List<Cliente> listCliente;
    private javax.swing.JPanel painelAcaoAparelho;
    private javax.swing.JPanel painelDadosAparelho;
    private javax.swing.JPanel painelNavegacao;
    private javax.swing.JTable tblAparelho;
    private javax.swing.JTextField txtCodigoAparelho;
    private javax.swing.JLabel txtCodigoAparelhos;
    private javax.swing.JFormattedTextField txtDataGarantia;
    private javax.swing.JFormattedTextField txtDataRecebimento;
    private javax.swing.JTextField txtMarcaAparelho;
    private javax.swing.JLabel txtMarcaAparelhos;
    private javax.swing.JTextField txtNomeAparelho;
    private javax.swing.JLabel txtNomeAparelhos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
